Update annotations.config.ts
libs/designsystem/src/lib/components/chart/configs/annotations.config.ts:15:14 - error TS2739: Type '{ line: { borderDash: [number, number]; borderWidth: number; borderColor: string; }; ellipse: { borderDash: [number, number]; borderWidth: number; borderColor: string; backgroundColor: string; }; box: { ...; }; point: { ...; }; }' is missing the following properties from type 'AnnotationTypeRegistry': label, polygon